spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oli_saude?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  application:
    name: oliSaude

  jpa:
    hibernate:
      ddl-auto: update